[package]
name = "carolina-api"
version = "0.1.0"
edition = "2021"

[dependencies]
plugin-api = { path = "../plugin-api-rs" }
onebot-connect-interface = { path = "../onebot-connect/onebot-connect-interface" }
parking_lot = "0.12"
uuid = "1"
serde = "1"
thiserror = "2"
fxhash = "0.2"
bincode = { version = "1", optional = true }
dashmap = { version = "6", optional = true }

[features]
default = ["plugin", "framework"]
plugin = ["bincode"]
framework = ["dashmap"]
